INITIAL_PROVIDERS = [
    {
        "name": "Google AI",
        "official_pricing_url": "https://ai.google.dev/gemini-api/docs/pricing",
        "models": [
            {
                "name": "gemini-3.5-flash",
                "display_name": "Gemini 3.5 Flash",
                "recommended_task": "ocr_chat",
                "is_vision": True,
                "input_price_per_million": 1.50,
                "output_price_per_million": 9.00,
                "image_token_cost": 258,
            },
            {
                "name": "gemini-3.5-flash-chat",
                "display_name": "Gemini 3.5 Flash Chat",
                "recommended_task": "chat",
                "is_vision": False,
                "input_price_per_million": 1.50,
                "output_price_per_million": 9.00,
                "image_token_cost": 0,
            },
            {
                "name": "gemini-3.1-flash-lite",
                "display_name": "Gemini 3.1 Flash-Lite",
                "recommended_task": "ocr_chat",
                "is_vision": True,
                "input_price_per_million": 0.25,
                "output_price_per_million": 1.50,
                "image_token_cost": 258,
            },
            {
                "name": "gemini-3.1-flash-lite-chat",
                "display_name": "Gemini 3.1 Flash-Lite Chat",
                "recommended_task": "chat",
                "is_vision": False,
                "input_price_per_million": 0.25,
                "output_price_per_million": 1.50,
                "image_token_cost": 0,
            },
            {
                "name": "gemini-3.1-pro-preview",
                "display_name": "Gemini 3.1 Pro Preview",
                "recommended_task": "ocr_chat",
                "is_vision": True,
                "input_price_per_million": 2.00,
                "output_price_per_million": 12.00,
                "image_token_cost": 258,
            },
            {
                "name": "gemini-3.1-pro-preview-chat",
                "display_name": "Gemini 3.1 Pro Preview Chat",
                "recommended_task": "chat",
                "is_vision": False,
                "input_price_per_million": 2.00,
                "output_price_per_million": 12.00,
                "image_token_cost": 0,
            },
            {
                "name": "gemini-2.5-flash-lite",
                "display_name": "Gemini 2.5 Flash-Lite",
                "recommended_task": "ocr_chat",
                "is_vision": True,
                "input_price_per_million": 0.10,
                "output_price_per_million": 0.40,
                "image_token_cost": 258,
            },
            {
                "name": "gemini-2.5-flash-lite-chat",
                "display_name": "Gemini 2.5 Flash-Lite Chat",
                "recommended_task": "chat",
                "is_vision": False,
                "input_price_per_million": 0.10,
                "output_price_per_million": 0.40,
                "image_token_cost": 0,
            },
            {
                "name": "gemini-2.5-flash",
                "display_name": "Gemini 2.5 Flash",
                "recommended_task": "ocr_chat",
                "is_vision": True,
                "input_price_per_million": 0.30,
                "output_price_per_million": 2.50,
                "image_token_cost": 258,
            },
            {
                "name": "gemini-2.5-flash-chat",
                "display_name": "Gemini 2.5 Flash Chat",
                "recommended_task": "chat",
                "is_vision": False,
                "input_price_per_million": 0.30,
                "output_price_per_million": 2.50,
                "image_token_cost": 0,
            },
            {
                "name": "gemini-2.5-pro",
                "display_name": "Gemini 2.5 Pro",
                "recommended_task": "ocr_chat",
                "is_vision": True,
                "input_price_per_million": 1.25,
                "output_price_per_million": 10.00,
                "image_token_cost": 258,
            },
            {
                "name": "gemini-2.5-pro-chat",
                "display_name": "Gemini 2.5 Pro Chat",
                "recommended_task": "chat",
                "is_vision": False,
                "input_price_per_million": 1.25,
                "output_price_per_million": 10.00,
                "image_token_cost": 0,
            },
            {
                "name": "gemini-1.5-flash",
                "display_name": "Gemini 1.5 Flash",
                "recommended_task": "ocr",
                "is_vision": True,
                "input_price_per_million": 0.075,
                "output_price_per_million": 0.30,
                "image_token_cost": 258,
                "is_active": False,
            },
            {
                "name": "gemini-1.5-flash-chat",
                "display_name": "Gemini 1.5 Flash Chat",
                "recommended_task": "chat",
                "is_vision": False,
                "input_price_per_million": 0.075,
                "output_price_per_million": 0.30,
                "image_token_cost": 0,
                "is_active": False,
            },
            {
                "name": "gemini-1.5-pro",
                "display_name": "Gemini 1.5 Pro",
                "recommended_task": "ocr",
                "is_vision": True,
                "input_price_per_million": 1.25,
                "output_price_per_million": 5.00,
                "image_token_cost": 258,
                "is_active": False,
            },
            {
                "name": "gemini-1.5-pro-chat",
                "display_name": "Gemini 1.5 Pro Chat",
                "recommended_task": "chat",
                "is_vision": False,
                "input_price_per_million": 1.25,
                "output_price_per_million": 5.00,
                "image_token_cost": 0,
                "is_active": False,
            },
            {
                "name": "gemini-1.5-pro-user-reference",
                "display_name": "Gemini 1.5 Pro Usuario Ref.",
                "recommended_task": "ocr",
                "is_vision": True,
                "input_price_per_million": 1.50,
                "output_price_per_million": 9.00,
                "image_token_cost": 258,
                "is_active": False,
            },
        ],
    },
    {
        "name": "Groq",
        "official_pricing_url": "https://groq.com/pricing",
        "models": [
            {
                "name": "llama-3.2-11b-vision",
                "display_name": "Llama 3.2 11B Vision",
                "recommended_task": "ocr",
                "is_vision": True,
                "input_price_per_million": 0.18,
                "output_price_per_million": 0.18,
                "image_token_cost": 1600,
            },
            {
                "name": "llama-3.1-8b-instant",
                "display_name": "Llama 3.1 8B Instant",
                "recommended_task": "chat",
                "is_vision": False,
                "input_price_per_million": 0.05,
                "output_price_per_million": 0.08,
                "image_token_cost": 0,
            },
            {
                "name": "llama-3.3-70b",
                "display_name": "Llama 3.3 70B",
                "recommended_task": "chat",
                "is_vision": False,
                "input_price_per_million": 0.59,
                "output_price_per_million": 0.79,
                "image_token_cost": 0,
            },
        ],
    },
    {
        "name": "OpenAI",
        "official_pricing_url": "https://developers.openai.com/api/docs/pricing",
        "models": [
            {
                "name": "gpt-5.4-mini",
                "display_name": "GPT-5.4 mini",
                "recommended_task": "ocr_chat",
                "is_vision": True,
                "input_price_per_million": 0.75,
                "output_price_per_million": 4.50,
                "image_token_cost": 0,
            },
            {
                "name": "gpt-5.4-mini-chat",
                "display_name": "GPT-5.4 mini Chat",
                "recommended_task": "chat",
                "is_vision": False,
                "input_price_per_million": 0.75,
                "output_price_per_million": 4.50,
                "image_token_cost": 0,
            },
            {
                "name": "gpt-5.4-nano",
                "display_name": "GPT-5.4 nano",
                "recommended_task": "ocr_chat",
                "is_vision": True,
                "input_price_per_million": 0.20,
                "output_price_per_million": 1.25,
                "image_token_cost": 0,
            },
            {
                "name": "gpt-5.4-nano-chat",
                "display_name": "GPT-5.4 nano Chat",
                "recommended_task": "chat",
                "is_vision": False,
                "input_price_per_million": 0.20,
                "output_price_per_million": 1.25,
                "image_token_cost": 0,
            },
            {
                "name": "gpt-5-mini",
                "display_name": "GPT-5 mini",
                "recommended_task": "ocr_chat",
                "is_vision": True,
                "input_price_per_million": 0.25,
                "output_price_per_million": 2.00,
                "image_token_cost": 0,
            },
            {
                "name": "gpt-5-mini-chat",
                "display_name": "GPT-5 mini Chat",
                "recommended_task": "chat",
                "is_vision": False,
                "input_price_per_million": 0.25,
                "output_price_per_million": 2.00,
                "image_token_cost": 0,
            },
            {
                "name": "gpt-4.1-mini",
                "display_name": "GPT-4.1 mini",
                "recommended_task": "ocr_chat",
                "is_vision": True,
                "input_price_per_million": 0.40,
                "output_price_per_million": 1.60,
                "image_token_cost": 0,
            },
            {
                "name": "gpt-4.1-mini-chat",
                "display_name": "GPT-4.1 mini Chat",
                "recommended_task": "chat",
                "is_vision": False,
                "input_price_per_million": 0.40,
                "output_price_per_million": 1.60,
                "image_token_cost": 0,
            },
            {
                "name": "gpt-4o-mini",
                "display_name": "GPT-4o mini",
                "recommended_task": "ocr_chat",
                "is_vision": True,
                "input_price_per_million": 0.15,
                "output_price_per_million": 0.60,
                "image_token_cost": 0,
                "is_active": False,
            },
            {
                "name": "gpt-4o-mini-chat",
                "display_name": "GPT-4o mini Chat",
                "recommended_task": "chat",
                "is_vision": False,
                "input_price_per_million": 0.15,
                "output_price_per_million": 0.60,
                "image_token_cost": 0,
                "is_active": False,
            },
        ],
    },
    {
        "name": "Anthropic",
        "official_pricing_url": "https://www.anthropic.com/pricing",
        "models": [
            {
                "name": "claude-3.5-haiku",
                "display_name": "Claude 3.5 Haiku",
                "recommended_task": "chat",
                "is_vision": False,
                "input_price_per_million": 0.80,
                "output_price_per_million": 4.00,
                "image_token_cost": 0,
            }
        ],
    },
    {
        "name": "DeepSeek",
        "official_pricing_url": "https://api-docs.deepseek.com/quick_start/pricing",
        "models": [
            {
                "name": "deepseek-v3",
                "display_name": "DeepSeek V3",
                "recommended_task": "chat",
                "is_vision": False,
                "input_price_per_million": 0.14,
                "output_price_per_million": 0.28,
                "image_token_cost": 0,
            },
            {
                "name": "deepseek-r1",
                "display_name": "DeepSeek R1",
                "recommended_task": "chat",
                "is_vision": False,
                "input_price_per_million": 0.55,
                "output_price_per_million": 2.19,
                "image_token_cost": 0,
            },
        ],
    },
]

INITIAL_SCENARIOS = [
    {
        "name": "Bajo volumen",
        "description": "Validacion temprana con operacion chica.",
        "monthly_volume": 750,
        "incidence_rate": 0.15,
        "chat_turns": 2,
        "telecom_cost_per_session": 0,
        "infrastructure_monthly_cost": 0,
    },
    {
        "name": "Operacion normal",
        "description": "Escenario base para el MVP interno.",
        "monthly_volume": 3_000,
        "incidence_rate": 0.15,
        "chat_turns": 2,
        "telecom_cost_per_session": 0,
        "infrastructure_monthly_cost": 0,
    },
    {
        "name": "Campana alta",
        "description": "Pico de uso comercial con mayor volumen mensual.",
        "monthly_volume": 50_000,
        "incidence_rate": 0.18,
        "chat_turns": 2.5,
        "telecom_cost_per_session": 0,
        "infrastructure_monthly_cost": 0,
    },
    {
        "name": "Expansion regional",
        "description": "Volumen alto con infraestructura reforzada.",
        "monthly_volume": 150_000,
        "incidence_rate": 0.20,
        "chat_turns": 3,
        "telecom_cost_per_session": 0,
        "infrastructure_monthly_cost": 0,
    },
]
