"""Add RAG and Cache fields

Revision ID: 848c331b6869
Revises: 0001_initial
Create Date: 2026-06-15 19:18:31.579305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '848c331b6869'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_models', sa.Column('cached_input_price_per_million', sa.Float(), nullable=True))
    op.add_column('scenarios', sa.Column('rag_system_prompt_tokens', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('scenarios', sa.Column('rag_chunk_size', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('scenarios', sa.Column('rag_top_k', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenarios', 'rag_top_k')
    op.drop_column('scenarios', 'rag_chunk_size')
    op.drop_column('scenarios', 'rag_system_prompt_tokens')
    op.drop_column('ai_models', 'cached_input_price_per_million')
    # ### end Alembic commands ###
